{"name": "test_update_task_invalid_id", "status": "failed", "statusDetails": {"message": "AssertionError: Ответ пустой, запрос не удался\nassert None is not None", "trace": "self = <api.test_tasks.TestTasks object at 0x000001B61E363BE0>\n\n    @allure.description(\"Обновление задачи с несуществующим ID\")\n    def test_update_task_invalid_id(self):\n        with allure.step(\"Пробуем обновить задачу с фейковым ID\"):\n            fake_task_id=\"nope-task-000\"\n            data = {\"name\": \"Should not work\"}\n            response= self.api.update_task(fake_task_id, data)\n>           assert response is not None, \"Ответ пустой, запрос не удался\"\nE           AssertionError: Ответ пустой, запрос не удался\nE           assert None is not None\n\ntest_tasks.py:64: AssertionError"}, "description": "Обновление задачи с несуществующим ID", "steps": [{"name": "Пробуем обновить задачу с фейковым ID", "status": "failed", "statusDetails": {"message": "AssertionError: Ответ пустой, запрос не удался\nassert None is not None\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\tests\\api\\test_tasks.py\", line 64, in test_update_task_invalid_id\n    assert response is not None, \"Ответ пустой, запрос не удался\"\n"}, "start": 1749681308941, "stop": 1749681310535}], "start": 1749681308941, "stop": 1749681310536, "uuid": "85c1f6c5-5a60-4975-b601-cd7ac525f6c5", "historyId": "719d2b4da1dfef9b6adb89016e3ea409", "testCaseId": "719d2b4da1dfef9b6adb89016e3ea409", "fullName": "tests.api.test_tasks.TestTasks#test_update_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "10280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}