{"name": "test_update_task_invalid_id", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('self', <FixtureRequest for <Function test_update_task_invalid_id>>)", "trace": "file C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\tests\\api\\test_tasks.py, line 69\n  @allure.description(\"Обновление задачи с несуществующим ID\")\n  def test_update_task_invalid_id(self):\nE       fixture 'self' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, create_and_delete_task, doctest_namespace, list_id, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\tests\\api\\test_tasks.py:69"}, "description": "Обновление задачи с несуществующим ID", "start": 1749683182052, "stop": 1749683182052, "uuid": "11215d4d-749b-48c4-8377-225c1fd1c548", "historyId": "e752123c3bd266be76024d1ed99aa42f", "testCaseId": "e752123c3bd266be76024d1ed99aa42f", "fullName": "tests.api.test_tasks#test_update_task_invalid_id", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "20676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}