{"name": "test_login_invalid_credentials", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "page = <Page url='https://app.clickup.com/login'>\n\n    @allure.feature(\"UI: Авторизация ClickUp, негативный сценарий\")\n    @allure.description(\"Проверяем, что пользователь не может войти с неправильным логином или паролем\")\n    def test_login_invalid_credentials(page):\n        login_page = LoginPage(page)\n    \n        invalid_email = \"rtytr@yfgf.com\"\n        invalid_password = \"wrongpass\"\n    \n>       login_page.login_with(invalid_email, invalid_password)\n\ntest_login_page.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\pages\\login_page.py:29: in login_with\n    self.open()\n..\\..\\pages\\base_page.py:21: in open\n    self.page.goto(full_url)\n..\\..\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py:9024: in goto\n    self._sync(\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000001B79A392800>\ncb = <function Channel.send.<locals>.<lambda> at 0x000001B79A744AF0>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE             - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "description": "Проверяем, что пользователь не может войти с неправильным логином или паролем", "steps": [{"name": "Логинимся с email='rtytr@yfgf.com'", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\login_page.py\", line 29, in login_with\n    self.open()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 21, in open\n    self.page.goto(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9024, in goto\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Переход по адресу BASE_URL + endpoint", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 21, in open\n    self.page.goto(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9024, in goto\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Формируем полный URL из BASE и endpoint", "status": "passed", "start": 1749832391731, "stop": 1749832391731}], "start": 1749832391731, "stop": 1749832421770}], "parameters": [{"name": "email", "value": "'rtytr@yfgf.com'"}, {"name": "password", "value": "'wrongpass'"}], "start": 1749832391731, "stop": 1749832421771}], "start": 1749832391730, "stop": 1749832421772, "uuid": "5e864c89-9a4d-4c29-be16-3d9ca8794bca", "historyId": "071f92c4f67a6f129ce94efc090a7ec0", "testCaseId": "071f92c4f67a6f129ce94efc090a7ec0", "fullName": "tests.ui.test_login_page#test_login_invalid_credentials", "labels": [{"name": "feature", "value": "UI: Авторизация ClickUp, негативный сценарий"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "30964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}